### ISSUE TITLE
Rozumny verifikacny email

### ISSUE THREAD

**Issue by samoKrajci** [ZdruzenieSTROM/webstrom-backend#167]
Aktualne je email iba nejaky necitatelny token. Cheme aby
- to bolo citatelne pre cloveka
- tam bol link na ktory iba kliknes a hodi ta to na link. ten je nieco ako `/verify-email/<kod>` (ale, samozrejme, nech sa te generuje automaticky, url sa moze zmenit)

**Comment by kovacspe** [comment]
Treba upraviť v súboroch `/templates/account/email` Text mailov aby bol rozumnejší a aj subject abz z neho bolo jasné že sa jedná o STROMácku stránku.
