### ISSUE TITLE
Prelozit errorove hlasky pre registraciu

### ISSUE THREAD

**Issue by Matushl** [ZdruzenieSTROM/webstrom-backend#250]
Prelozit errorove hlasky pre endpoint registracie. Napriklad `A USER IS ALREADY REGISTERED WITH THIS E-MAIL ADDRESS`.

**Comment by Benji47** [comment]
Toto akože staci len zobrat ten text po slovensky a vsade ho tam preloziť to anglictiny?

**Comment by michalmasrna1** [comment]
Sorry za zle zadanie, ale to naopak treba prelozit tie ktore su po anglicky do slovenciny, tie ktore su v slovencine uz su dobre.

**Comment by kovacspe** [comment]
https://stackoverflow.com/questions/20467626/whats-the-correct-way-to-set-up-django-translation 
https://docs.djangoproject.com/en/4.2/topics/i18n/translation/
... Takto sa riesi translation
ale neviem zatial ako zistit co sa vobec da prekladat
