### ISSUE TITLE
Počet komentárov v diskusii k príkladom

### ISSUE THREAD

**Issue by Ericius208** [ZdruzenieSTROM/webstrom-backend#277]
Užívateľ bez autorizácie vidieť neschválenené komentáre ich veru nevidí, ale rátajú sa mu do súčtu v zátvorke v buttone Diskusia(počet komentárov).

**Comment by rtrembecky** [comment]
coo, to sa da? 😮 cool!

**Comment by Matushl** [comment]
> a nie je to teda problem s fixtures (predvyplnenymi datami), ktorych stav nedava zmysel? ale co citam, co pisete, hej, Peto chcel tie permissions este celkovo nejak lepsie prejst, zatial na tom nebol uplne velky zretel... bude to treba aj pre admina

ano, moze to byt issue tych fixtures, ale popravde problem vidim aj v tom, ze veduci krickov videl nezverejnene komentare na strome, co by nemal podla mna

**Comment by kovacspe** [comment]
Fixture obsahuju aktuálne už iba 2 zverejnené komentáre. Takže ak ten problém nastáva aj teraz tak je to zrejme problém v počítaní na BE
