### ISSUE TITLE
Posts - PATCH - special handling for nested links

### ISSUE THREAD

**Issue by rtrembecky** [ZdruzenieSTROM/webstrom-backend#327]
v PATCHi posleme array `links`, ktory moze vyzerat:
```json
[
  {
    "id": 0,
    "caption": "Prihlásenie",
    "url": "https://seminar.strom.sk/sk/prispevky/"
  },
  {
    "caption": "xxx",
    "url": "htttp://asdfsad"
  }
]
```
treba:
- zmazat linky s `id`, ktore chybaju oproti originalnemu stavu objektu
- updatnut zvysne linky  s `id`
- vytvorit linky bez `id`

**Comment by kovacspe** [comment]
@rtrembecky vyzera ze to uz tak funguje

**Comment by rtrembecky** [comment]
yop
